[Unit]
After=network-online.target iriumd.service irium-pool-shim.service
Wants=network-online.target iriumd.service irium-pool-shim.service
Requires=iriumd.service irium-pool-shim.service

[Service]
EnvironmentFile=-/etc/irium/iriumd.env
Restart=always
RestartSec=2
